### ISSUE TITLE
Simple frontend

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-ethical-metrics#45]
Simple frontend for:
- Show instance
- Show instance registered or not
- Register and Unregister buttons

**Comment by Marketen** [comment]
Since frontend needs access to instance file, it needs a proper backend with access to filesystem (done with express.js).

As discussed with devs, frontend should have the following functionalities:
- register/unregister instance
- check instance status on monitor proxy

for now, email should NOT be able to be changed through the frontend (only in pkg config).
